;;; use ctrl + h/j/k/l to move cursor
(global-set-key (kbd "C-h") nil)   
(global-set-key (kbd "C-j") nil)       
(global-set-key (kbd "C-k") nil)   
(global-set-key (kbd "C-l") nil)    
(global-set-key (kbd "C-h") 'backward-char)   
(global-set-key (kbd "C-j") 'next-line)       
(global-set-key (kbd "C-k") 'previous-line)   
(global-set-key (kbd "C-l") 'forward-char)    
(global-set-key (kbd "C-c h") 'help-command)  
(provide 'init-keys)
